export const tileSprites = {
  tile1: "tile1",
  tile3: "tile3",
  tileComplete: "tile1Complete",
  tileTrimmed: "tile1Trimmed",
  rBoard: "rightBoard",
  lBoard: "leftBoard",
  cactusB: "cactusBig",
  cactusS: "cactusSmall",
  cactusO: "trueCactus",
  tree: "tree",
  completePillar: "completePillar",
  pillarRoof: "pillarRoof",
  pillarRoof2: "pillarRoof2",
  redMushroom: "mushroomRed",
  yellowMushroom: "mushroomYellow",
  ladder: "ladder",
  fHeart: "fullHeart",
  hHeart: "halfHeart",
  eHeart: "emptyHeart",
  flag: ["flag1", "flag2"],
  coins: ["coin1", "coin2"],
};
export const aboutMeBg = [
  {
    name: tileSprites.rBoard,
    grounded: true,
    animated: false,
    x: 0,
  },
  {
    name: tileSprites.cactusO,
    grounded: true,
    animated: false,
    x: 300,
  },
  {
    name: tileSprites.cactusS,
    grounded: true,
    animated: false,
    x: 30,
  },
  {
    name: tileSprites.cactusO,
    grounded: true,
    animated: false,
    x: 300,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 50,
  },
  {
    name: tileSprites.tree,
    grounded: true,
    animated: false,
    x: 275,
  },
  {
    name: tileSprites.cactusB,
    grounded: true,
    animated: false,
    x: 70,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 30,
  },
  {
    name: tileSprites.rBoard,
    grounded: true,
    animated: false,
    x: 100,
  },
  {
    name: tileSprites.completePillar,
    grounded: true,
    animated: false,
    x: 175,
  },
  {
    id: "pillarRoof",
    name: tileSprites.pillarRoof,
    grounded: false,
    animated: false,
    x: -11,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof2,
    grounded: false,
    animated: false,
    x: 96,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof2,
    grounded: false,
    animated: false,
    x: 96,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof,
    grounded: false,
    animated: false,
    x: 132,
    y: 174,
    flipX: true,
  },
  {
    name: tileSprites.completePillar,
    grounded: true,
    animated: false,
    x: -46,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 30,
  },
  {
    name: tileSprites.rBoard,
    grounded: true,
    animated: false,
    x: 120,
    id: "skillBoard",
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 220,
  },
  {
    id: "java",
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 132,
    y: 174,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    name: tileSprites.hHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    id: "spring",
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: -280,
    y: 100,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    id: "fe",
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: -280,
    y: 26,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    id: "react",
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 280,
    y: 174,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 174,
  },
  {
    id: "docker",
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: -280,
    y: 100,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 100,
  },
  {
    id: "aws",
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: -280,
    y: 26,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    name: tileSprites.fHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
  {
    name: tileSprites.eHeart,
    grounded: false,
    animated: false,
    x: 70,
    y: 26,
  },
];

export const aboutMeBgTwo = [
  {
    name: tileSprites.yellowMushroom,
    grounded: true,
    animated: false,
    x: 70,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: -75,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 95,
  },
  {
    name: tileSprites.rBoard,
    grounded: true,
    animated: false,
    x: 150,
    id: "experience",
  },
  {
    name: tileSprites.flag,
    grounded: true,
    animated: true,
    x: 250,
    id: "expFlag",
  },
  {
    name: tileSprites.flag,
    grounded: true,
    animated: true,
    x: 208,
  },
  {
    name: tileSprites.completePillar,
    grounded: true,
    animated: false,
    x: 175,
  },
  {
    id: "ibm",
    name: tileSprites.pillarRoof,
    grounded: false,
    animated: false,
    x: -11,
    y: 174,
  },
  {
    id: "ibmyear",
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: -36,
  },
  {
    name: tileSprites.pillarRoof2,
    grounded: false,
    animated: false,
    x: 132,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof2,
    grounded: false,
    animated: false,
    x: 96,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof,
    grounded: false,
    animated: false,
    x: 132,
    y: 174,
    flipX: true,
  },
  {
    name: tileSprites.completePillar,
    grounded: true,
    animated: false,
    x: -46,
  },
  {
    name: tileSprites.yellowMushroom,
    grounded: true,
    animated: false,
    x: 56,
  },
];

export const aboutMeBgThree = [
  {
    name: tileSprites.completePillar,
    grounded: true,
    animated: false,
    x: 175,
  },
  {
    id: "deloitte",
    name: tileSprites.pillarRoof,
    grounded: false,
    animated: false,
    x: -11,
    y: 174,
  },
  {
    id: "deloitteyear",
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: -36,
  },
  {
    name: tileSprites.pillarRoof2,
    grounded: false,
    animated: false,
    x: 132,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof2,
    grounded: false,
    animated: false,
    x: 96,
    y: 174,
  },
  {
    name: tileSprites.pillarRoof,
    grounded: false,
    animated: false,
    x: 132,
    y: 174,
    flipX: true,
  },
  {
    name: tileSprites.completePillar,
    grounded: true,
    animated: false,
    x: -46,
  },
  {
    name: tileSprites.yellowMushroom,
    grounded: true,
    animated: false,
    x: 56,
  },
];

export const aboutMeBgFour = [
  {
    name: tileSprites.yellowMushroom,
    grounded: true,
    animated: false,
    x: 56,
    id: "contactme",
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 30,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 130,
  },
  {
    name: tileSprites.redMushroom,
    grounded: true,
    animated: false,
    x: 30,
  },
];
export const aboutMeTextRel = [
  {
    text: "WELCOME",
    x: 20,
    y: 0,
    size: 18,
    style: "Secondary",
    id: "pillarRoof",
  },
  {
    text: "Skills",
    x: -40,
    y: 0,
    size: 18,
    style: "primary",
    id: "skillBoard",
  },
  {
    text: "Java",
    x: -76,
    y: -30,
    size: 18,
    style: "Secondary",
    id: "java",
  },
  {
    text: "Spring boot",
    x: -198,
    y: -30,
    size: 18,
    style: "Secondary",
    id: "spring",
  },
  {
    text: "html,css,js",
    x: -198,
    y: -30,
    size: 18,
    style: "Secondary",
    id: "fe",
  },
  {
    text: "React",
    x: -90,
    y: -30,
    size: 18,
    style: "Secondary",
    id: "react",
  },
  {
    text: "Docker",
    x: -108,
    y: -30,
    size: 18,
    style: "Secondary",
    id: "docker",
  },
  {
    text: "AWS",
    x: -54,
    y: -30,
    size: 18,
    style: "Secondary",
    id: "aws",
  },
  {
    text: "Experience",
    x: -90,
    y: 0,
    size: 18,
    style: "primary",
    id: "experience",
  },
  {
    text: "4 Yrs",
    x: 52,
    y: 52,
    size: 26,
    style: "primary",
    id: "expFlag",
  },
  {
    text: "Life at IBM",
    x: 52,
    y: 0,
    size: 20,
    style: "secondary",
    id: "ibm",
  },
  {
    text: "2021",
    x: 162,
    y: 0,
    size: 26,
    style: "primary",
    id: "ibmyear",
  },
  {
    text: "Delighted in Deloitte",
    x: 52,
    y: 0,
    size: 20,
    style: "secondary",
    id: "deloitte",
  },
  {
    text: "2022",
    x: 162,
    y: 0,
    size: 26,
    style: "secondary",
    id: "deloitteyear",
  },
  {
    text: "contact me",
    x: 162,
    y: 0,
    size: 26,
    style: "secondary",
    id: "contactme",
  },
];

export const aboutMeText = [
  {
    text: "Little about me",
    x: 0,
    y: 22,
    size: 18,
    style: "primary",
  },
  {
    text: "Idris",
    x: 330,
    y: 2,
    size: 24,
    style: "primary",
  },
  {
    text: "Full Stack Java Developer",
    x: -330,
    y: 40,
    size: 18,
    style: "primary",
  },
];

export const aboutEndText = [
  {
    text: "where do you think you are going ?",
    x: 100,
    y: 22,
    size: 18,
    style: "primary",
  },
  {
    text: "Road ends here . . .",
    x: 600,
    y: 22,
    size: 18,
    style: "primary",
  },
  {
    text: "I did not handle X-Axis, the ground will fall",
    x: 800,
    y: 22,
    size: 18,
    style: "primary",
  },
  {
    text: "Here take some gold coins and turn back",
    x: 1000,
    y: 22,
    size: 18,
    style: "primary",
  },

  {
    text: "Since you made it so far I want to thank you and wish you best of luck :)",
    x: 500,
    y: 22,
    size: 18,
    style: "primary",
  },
]

export const projectsText = [
  {
    title: "Application Modernization",
    text: "Rewriting of old legacy applications to new cloud friendly versions, My Client was AT&T",
    x: 200,
    y: 250,
  },
  {
    title: "Scrapers for Mainframes",
    text: "Using Java IO Streams. Which helped teams to use the wrapper in their project.",
    x: 500,
    y: 250,
  },
  {
    title: "ETL Orchestration Engine",
    text: "decouple ETL processes using JAVA, Spring boot and React Js",
    x: 500,
    y: 250,
  },
];

export const projectsDeloitte = [
  {
    title: "Health Care Product",
    text: "Was working on config driven application for a US based client",
    x: 200,
    y: 250,
  },
  {
    title: "ETL middle ware",
    text: "was building and maintain middle ware for SAP and legacy systems for Ford Motor company",
    x: 500,
    y: 250,
  },
  {
    title: "And many more",
    text: "I have list only a few projects in this resume contact me to know more ",
    x: 500,
    y: 250,
  },
];

export const credits = [
  {
    title: "Sprites Credit :  kenney",
    text: "Website : www.kenney.nl got my background and other sprites from here do support him",
    x: 200,
    y: 250,
  },
  {
    title: "Sprite cred: sanderfrenken",
    text: "great tool refer credits.csv in my repo to get a list of all the contributors",
    x: 500,
    y: 250,
  },
];
export const coins = [
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 1050,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    id: "coin",
    animated: true,
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    id: "coin",
    animated: true,
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    id: "coin",
    animated: true,
    x: 534,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    id: "coin",
    animated: true,
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: false,
    animated: true,
    id: "coin",
    x: 0,
    y: 54,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: false,
    animated: true,
    id: "coin",
    x: 0,
    y: 54,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 2344,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 1950,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
];


export const endCoins = [
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 3150,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: false,
    animated: true,
    id: "coin",
    x: 0,
    y: 54,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
  {
    name: tileSprites.coins,
    grounded: false,
    animated: true,
    id: "coin",
    x: 0,
    y: 54,
  },
  {
    name: tileSprites.coins,
    grounded: true,
    animated: true,
    id: "coin",
    x: 50,
  },
]